### ISSUE TITLE
Encrypted cleaned dataset

### ISSUE THREAD

**Issue by goku2130** [vitoralbiero/id_versus_selfie_chiya#1]
Hi Vitor,

Thank you for such an amazing work.

I would like to use the results of chiya to retrain on different racial demographics (african american, white, asian, etc) in general and share the results. To begin, I wanted to replicate with the IvS dataset that is mentioned in your paper. The dataset link is working but the cleaned images are encrypted. Could you please share the cleaned IvS dataset? It would be really helpful to save efforts.

I would also like to know your thoughts on retraining strategies.

Thanks  
Gokul

**Comment by goku2130** [comment]
I had sent a mail asking for access. Eventually, I received the password through the mail (quickly). Thanks Vitor

**Comment by mchaitanyak35** [comment]
Hi Vitor,

Even I am trying to replicate your work on IvS dataset on a different region. The dataset is accessible but zip file is encrypted with password. If you can share the cleaned IvS data set that would help me save a lot of my efforts.

I tried to find your email address to directly reach out to you. But I couldn't find it anywhere, so reaching out through this way.

Thanks,
Krishna
